### PR TITLE
Updated readmes

### PR DESCRIPTION
**Pull request by JasmineDeng**
Updated READMEs and put in a frame for adding backend information when the repositories are merged. 

The parts that should be replaced with backend information or just deleted are bolded in brackets [].

### CODE REVIEW

**Comment by btburton42** [comment]
has this been rebased against current master?

**Comment by btburton42** [comment]
is the intention to merge @stevenelleman's highlight branch in this as well?

**Comment by JasmineDeng** [comment]
it's been rebased, and i only changed the README and CONTRIBUTING doc so you can merge it but i don't think it makes a difference either way (since the two aren't related).

**Comment by btburton42** [comment]
this commit includes a lot of highlighter code is why i'm asking. is that the intention?

**Comment by JasmineDeng** [comment]
oh yes, sorry, that's because at one point I was working with Steven and then diverged to work solely on the READMEs. the highlighter code here isn't complete, so I'll just make the highlighter code the same as the code on master and make another request.

**Comment by btburton42** [comment]
@JasmineDeng you can also use `git rebase --onto` to remove that commit if you want to practise some git-fu. 😄  here's a link to the process whereby you remove a commit from your branch with a single command (https://blog.pivotal.io/labs/labs/git-rebase-onto).

**Pull request closed without merging**
