### PR TITLE
namespace our object properly

### PR DESCRIPTION
**Pull request by btburton42**

### CODE REVIEW

**Comment by nickbadams** [comment]
M

**Comment by nickbadams** [comment]
My only concern with merging this immediately is that the backend may have changed slightly so that we are no longer using a 'tua' object...

**Comment by btburton42** [comment]
is this a change that is live in the API?

**Comment by btburton42** [comment]
yeah now i'm seeing this call here that's failing.

`https://text-thresher.herokuapp.com/api/articles`

when it should be fetching a JSON blob from here `https://text-thresher.herokuapp.com/api/articles/?format=json`

hmm. the API needs documentation. endpoints are unclear.

**Comment by btburton42** [comment]
this might even just still be using mock data, which would be bad. first priority should be wiring this up to fetch actual articles from the backend.

**Comment by mngyuan** [comment]
hello - the heroku backend is unreliable, there was some parallel work that @p-patil and flora / vivian were working on, so for a bit I was using the heroku. But Vivian / Flora talked with me about the proper structure of the data and their version of the backend more properly reflects what the frontend code expects... there'll be some unraveling that has to be done that I guess we'll talk about at our next meeting

It doesn't use mock data and it should properly load stuff from the backend @btburton42, you just have to set up and use the backend repo. I've got code on the `redux-topics` branch that works for sure, but the stuff on master should also be working...

**Pull request closed without merging**
